repos: 
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks: 
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks: 
      - id: flake8

  - id: python-check
    name: py_compile
    entry: python -m py_compile app.py app_components/*.py
    language: python
