services:
  - type: web
    name: casino-calendar
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      NPM_CONFIG_PRODUCTION=false npm install
      npm run build:css
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
