services:
  - type: web
    name: casino-calendar
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npm install
      python -m py_compile app.py app_components/*.py
      black --check .
      isort --check-only .
      flake8 .
      npm run build:css
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
