# Stub file for plotly.graph_objs
from typing import Any, Union

class Scatter:
    def __init__(self, **kwargs: Any) -> None: ...

class Layout:
    def __init__(self, **kwargs: Any) -> None: ...

class Figure:
    def __init__(self, data: Any = None, layout: Any = None, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
