services:
  - type: web
    name: casino-calendar
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npm ci
      python -m py_compile \
        app.py \
        app_components/*.py \
        app_components/callbacks/*.py \
        utils/*.py
      black --check .
      isort --check-only --settings-path config/formatting/.isort.cfg .
      flake8 --config config/linting/.flake8 .
      npm run build:css
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
